# yamllint disable rule:line-length
---
name: driftctl

description: Run driftctl assessment.

inputs:

  working-directory:
    description: Set working directory. Default is ./.
    required: false
    default: "."

  driftctl-version:
    description: |
      Specify driftctl version to perform scan. Set version "installed" to
      perform scan with the version already installed on the Runner.
    required: false
    default: ""

  driftctl-additional-args:
    description: Provide additional commandline arguments.
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: driftctl scan of terraform files or plan
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        #!/usr/bin/env bash
        if [[ "${{ inputs.driftctl-version }}" != "" ]]; then
          echo "Perform driftctl scan"
          driftctl version
          driftctl ${{ inputs.driftctl-additional-args }}
        fi
