# yamllint disable rule:line-length
---
name: infracost

description: Run infracost assessment.

inputs:

  working-directory:
    description: Set working directory. Default is ./.
    required: false
    default: "."

  infracost-version:
    description: |
      Specify infracost version to perform scan. Set version "installed" to
      perform scan with the version already installed on the Runner.
    required: false
    default: ""

  infracost-additional-args:
    description: Provide additional commandline arguments.
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: infracost scan of terraform files or plan
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        #!/usr/bin/env bash
        if [[ "${{ inputs.infracost-version }}" != "" ]]; then
          echo "Perform infracost assessment"
          infracost --version
          infracost ${{ inputs.infracost-additional-args }}
        fi
