# yamllint disable rule:line-length
---
name: tfsec

description: Run tfsec scan in working-directory.

inputs:

  working-directory:
    description: specific folder in which to run the commands
    required: false
    default: "."

  tfsec-version:
    description: |
      Perform tfsec scan of terraform files. Specify version "installed" to use
      the version already installed on the executor.
    required: false
    default: ""

  tfsec-additional-args:
    description: Provide additional tfsec commandline arguments.
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: tfsec scan of terraform files
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        #!/usr/bin/env bash
        if [[ "${{ inputs.tfsec-version }}" != "" ]]; then
          echo "Perform tfsec scan"
          tfsec --version
          tfsec ${{ inputs.tfsec-additional-args }}
        fi
