# yamllint disable rule:line-length
---
name: snyk IaC

description: Run snyk scan in working-directory.

inputs:

  working-directory:
    description: Set working directory. Default is ./.
    required: false
    default: "."

  terraform-plan-outfile:
    description: Provide name of terraform plan output file for targeted scan.
    required: false
    default: ""

  snyk-version:
    description: |
      Specify snyk version to perform scan. Set version "installed" to
      perform scan with the version already installed on the Runner.
    required: false
    default: ""

  snyk-organization:
    description: Snyk organisation name.
    required: false
    default: ""

  snyk-token:
    description: Snyk API token.
    required: false
    default: ""

  snyk-additional-args:
    description: Provide additional commandline arguments.
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: snyk scan of terraform files or plan
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        #!/usr/bin/env bash
        if [[ "${{ inputs.snyk-version }}" != "" ]]; then
          echo "Perform snyk scan"
          export SNYK_TOKEN=${{ inputs.snyk-token }}
          snyk --version
          snyk iac test --org=${{ inputs.snyk-organization }} ${{ inputs.checkov-additional-args }} ${{ inputs.terraform-plan-outfile }}
        fi
