# yamllint disable rule:line-length
---
run-name: Terraform plan

on:
  workflow_call:

    inputs:

      working-directory:
        description: Set working directory. Default is ./.
        required: false
        type: string
        default: .

      cosign-version:
        description: Specify cosign version.
        required: false
        type: string
        default: "2.2.0"

      terraform-version:
        description: |
          If you specify a specific version, it will be installed and used by
          all orb terraform functions. Leave blank or specify version "installed"
          to use the version already installed on the executor.
        required: false
        type: string
        default: ""

      terraform-init-additional-args:
        description: |
          Include any additional terraform init command arguments.
          Default is -backend=false.
        required: false
        type: string
        default: -backend=false

      tflint-version:
        description: |
          Specify tflint version to perform scan. Set version "installed" to
          perform scan with the version already installed on the Runner.
        required: false
        type: string
        default: ""

      tflint-provider:
        description: Cloud provider. aws, google, or azurerm
        required: false
        type: string
        default: ""

      tflint-provider-version:
        description: Provider plugin version.
        required: false
        type: string
        default: ""

      tflint-additional-args:
        description: |
          Include any additional tflint commandline arguments. Note: not all
          options can be successfully used in a pipeline.
        required: false
        type: string
        default: ""

      tfsec-version:
        description: |
          Specify tfsec version to perform scan. Set version "installed" to
          perform scan with the version already installed on the Runner.
        required: false
        type: string
        default: ""

      tfsec-additional-args:
        description: |
          Include any additional tfsec commandline arguments.
        required: false
        type: string
        default: ""

      checkov-version:
        description: |
          Perform checkov scan of terraform files without plan output. Specify
          version "installed" to use the version already installed on the executor.
        required: false
        type: string
        default: ""

      checkov-additional-args:
        description: |
          Include any additional checkov commandline arguments.
        required: false
        type: string
        default: "-d ."

      snyk-version:
        description: |
          Perform snyk IaC scan of terraform files without plan output. Specify
          version "installed" to use the version already installed on the executor.
        required: false
        type: string
        default: ""

      snyk-organization:
        description: Snyk organisation name.
        required: false
        type: string
        default: ""

      snyk-token:
        description: Snyk API token.
        required: false
        type: string
        default: $SNYK_TOKEN

      snyk-additional-args:
        description: Provide additional commandline arguments.
        required: false
        type: string
        default: ""

      terrascan-version:
        description: |
          Perform terrascan scan of terraform files without plan output. Specify
          version "installed" to use the version already installed on the executor.
        required: false
        type: string
        default: ""

      terrascan-init-args:
        description: Provide custom init command flags.
        required: false
        type: string
        default: ""

      terrascan-iac-type:
        description: terrascan iac provider types.
        required: false
        type: string
        default: ""

      terrascan-policy-type:
        description: terrascan preset policy types. Default is all.
        required: false
        type: string
        default: "all"

      terrascan-custom-scan-args:
        description: |
          Override default settings with any valid terrascan scan flags.
        required: false
        type: string
        default: ""

      driftctl-version:
        description: Specify driftctl version or "installed" to perform scan. Leave blank to skip.
        required: false
        type: string
        default: ""

      drift-additional-args:
        description: Provide additional commandline arguments.
        required: false
        type: string
        default: ""

      infracost-version:
        description: Specify infracost version or "installed" to perform scan. Leave blank to skip.
        required: false
        type: string
        default: ""

      infracost-api-key:
        description: organization api key
        type: string
        default: $INFRACOST_API_KEY

      infracost-additional-args:
        description: Provide flag options to scan command.
        type: string
        default: ""

      trivy-version:
        description: Specify trivy version or "installed" to perform scan. Leave blank to skip.
        required: false
        type: string
        default: ""

      trivy-additional-args:
        description: Provide additional trivy commandline arguments.
        required: false
        type: string
        default: "config . --exit-code 1"

      before-plan:
        description: Optional steps to run before running terraform plan
        required: false
        type: string
        default: echo "none"

      after-plan:
        description: Optional steps to run before after terraform plan
        required: false
        type: string
        default: echo "none"

jobs:

  terraform-static-code-analysis:
    name: terraform static code analysis
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1

      - name: install terraform workflow packages
        uses:  gowthamshankar99/terraform-actions/packages@main
        with:
          working-directory: ${{ inputs.working-directory }}
          cosign-version: ${{ inputs.cosign-version }}
          terraform-version: ${{ inputs.terraform-version }}
          tflint-version: ${{ inputs.tflint-version }}
          tfsec-version: ${{ inputs.tfsec-version }}
          checkov-version: ${{ inputs.checkov-version }}
          snyk-version: ${{ inputs.snyk-version }}
          terrascan-version: ${{ inputs.terrascan-version }}
          driftctl-version: ${{ inputs.driftctl-version }}
          infracost-version: ${{ inputs.infracost-version }}
          trivy-version: ${{ inputs.trivy-version }}

      - name: run custom before-analysis scripts
        working-directory: ${{ inputs.working-directory }}
        shell: bash
        run: ${{ inputs.before-static-analysis }}

      - name: terraform init
        working-directory: ${{ inputs.working-directory }}
        shell: bash
        run: |
          terraform version
          terraform init ${{ inputs.terraform-init-additional-args }}

      - name: evaluate canonical format of terraform files 
        working-directory: ${{ inputs.working-directory }}
        shell: bash
        run: terraform fmt -check=false

      - name: validate terraform syntax
        working-directory: ${{ inputs.working-directory }}
        shell: bash
        run: terraform validate

      - name: optional tflint scan of terraform source files
        uses:  gowthamshankar99/terraform-actions/tflint@main
        with:
          working-directory: ${{ inputs.working-directory }}
          tflint-version: ${{ inputs.tflint-version }}
          tflint-provider: ${{ inputs.tflint-provider }}
          tflint-provider-version: ${{ inputs.tflint-provider-version }}
          tflint-additional-args: ${{ inputs.tflint-additional-args }}

      - name: optional tfsec scan of terraform source files
        uses:  gowthamshankar99/terraform-actions/tfsec@main
        with:
          working-directory: ${{ inputs.working-directory }}
          tfsec-version: ${{ inputs.tfsec-version }}
          tfsec-additional-args: ${{ inputs.tfsec-additional-args }}

      - name: optional checkov scan of terraform source files
        uses:  gowthamshankar99/terraform-actions/checkov@main
        with:
          working-directory: ${{ inputs.working-directory }}
          checkov-version: ${{ inputs.checkov-version }}
          checkov-additional-args: ${{ inputs.checkov-additional-args }}

      - name: optional snyk scan of terraform source files
        uses:  gowthamshankar99/terraform-actions/snyk@main
        with:
          working-directory: ${{ inputs.working-directory }}
          snyk-version: ${{ inputs.snyk-version }}
          snyk-organization: ${{ inputs.snyk-organization }}
          snyk-token: ${{ inputs.snyk-token }}
          snyk-additional-args: ${{ inputs.snyk-additional-args }}

      - name: optional terrascan scan of terraform source files
        uses:  gowthamshankar99/terraform-actions/terrascan@main
        with:
          working-directory: ${{ inputs.working-directory }}
          terrascan-version: ${{ inputs.terrascan-version }}
          terrascan-init-args: ${{ inputs.terrascan-init-args }}
          terrascan-iac-type: ${{ inputs.terrascan-iac-type }}
          terrascan-policy-type: ${{ inputs.terrascan-policy-type }}

      - name: optional driftctl assessment
        uses:  gowthamshankar99/terraform-actions/driftctl@main
        with:
          working-directory: ${{ inputs.working-directory }}
          driftctl-version: ${{ inputs.driftctl-version }}
          driftctl-additional-args: ${{ inputs.driftctl-additional-args }}

      - name: optional trivy scan
        uses:  gowthamshankar99/terraform-actions/trivy@main
        with:
          working-directory: ${{ inputs.working-directory }}
          trivy-version: ${{ inputs.trivy-version }}
          trivy-additional-args: ${{ inputs.trivy-additional-args }}

      - name: run custom after-analysis scripts
        working-directory: ${{ inputs.working-directory }}
        shell: bash
        run: ${{ inputs.after-static-analysis }}

      # echo "action_state=yellow" >> "$GITHUB_ENV"

      - name: terraform init
        working-directory: ${{ inputs.working-directory }}
        run: |
          terraform plan -out tfplan.json

      - name: output the plan 
        working-directory: ${{ inputs.working-directory }}
        run: | 
          cat tfplan.json
